spring.application.name=flightOnTime

##-------------------------DATABASE-----------------------------#

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:mysql://localhost/${DB_NAME}

spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

##-------------------MICROSERVICE FLASK-------------------------#
oracle.prediction.url=${ORACLE_PREDICTION_URL}

##-----------------------WEATHER API----------------------------#
weather.api.url=${WEATHER_API_URL}

#spring.profiles.active=mock-oracle